- name: deploy CD
  hosts:   
    - 192.168.101.31
    - 192.168.101.32  
  #gather_facts: yes
  remote_user: root
  vars:
      recursion: yes
      servers:
              - { hostname: kube-worker01, ip: 192.168.101.31 }
              - { hostname: kube-worker02, ip: 192.168.101.32 }

      ansible_python_interpreter: "{{ ansible_playbook_python }}"    
  #become: yes

  tasks:

      - name: Install apache
        yum:
          name: apache2
          state: present
          update_cache: yes


      - name: install Maven
        yum:
          name: maven
          state: present
          update_cache: yes


      - name: Install git
        yum:
          name: git
          state: present
          update_cache: yes

      - name: Install Supporting Software
        yum:
          name: software-properties-common
          state: present

      - name: Install python
        yum:
          name: python3.8
          state: present

      - name: install Java
        yum:
          name: openjdk-8-jdk
          state: present
          update_cache: yes

      
      - name: install Docker
        yum:
          name: docker
          state: present
          update_cache: yes

      - name: Install docker-compose
        remote_user: root
        get_url: 
          url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
          dest: /usr/local/bin/docker-compose
          mode: 'u+x,g+x'


 
  handlers:
   #- name: restart apache2
   #   service: name=apache2 state=restarted
